---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 4

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
- name: windows_2012r2
  driver_config:
    box: mwrock/Windows2012R2
    communicator: winrm
    vm_hostname: false
  transport:
    name: winrm


suites:
  - name: default
    run_list:
      - recipe[win2012r2::default]
    attributes: